In [1]:
import numpy as np

# Step 1: Setup
np.random.seed(42)  # reproducibility
num_students = 100
num_subjects = 5
subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

# Step 2: Generate random marks (0–100)
marks = np.random.randint(30, 101, size=(num_students, num_subjects))  # (100 x 5)

print("Marks Matrix (first 5 students):\n", marks[:5])

# Step 3: Average per student (row-wise)
avg_per_student = np.mean(marks, axis=1)

# Step 4: Average per subject (column-wise)
avg_per_subject = np.mean(marks, axis=0)

# Step 5: Highest scorer (overall)
best_student_idx = np.argmax(avg_per_student)
best_student_score = avg_per_student[best_student_idx]

# Step 6: Subject difficulty (lowest avg score)
toughest_subject_idx = np.argmin(avg_per_subject)

# Step 7: Display Insights
print("\n Student Marks Analysis:")

print("\nAverage Marks per Student (first 5):")
for i in range(5):
    print(f"Student {i+1}: {avg_per_student[i]:.2f}")

print("\nAverage Marks per Subject:")
for subj, avg in zip(subjects, avg_per_subject):
    print(f"{subj}: {avg:.2f}")

print(f"\n Best Student: Student {best_student_idx+1} "
      f"with Avg = {best_student_score:.2f}")

print(f"Toughest Subject: {subjects[toughest_subject_idx]} "
      f"(Avg = {avg_per_subject[toughest_subject_idx]:.2f})")


Marks Matrix (first 5 students):
 [[81 44 90 50 53]
 [32 51 82 31 59]
 [67 31 93 89 50]
 [62 87 51 78 88]
 [71 89 44 91 91]]

 Student Marks Analysis:

Average Marks per Student (first 5):
Student 1: 63.60
Student 2: 51.00
Student 3: 66.00
Student 4: 73.20
Student 5: 77.20

Average Marks per Subject:
Math: 64.68
Physics: 64.30
Chemistry: 63.28
English: 64.67
Computer: 66.47

 Best Student: Student 6 with Avg = 84.80
Toughest Subject: Chemistry (Avg = 63.28)
